/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Album: { // root type
    Artist?: NexusGenRootTypes['Artist'] | null; // Artist
    ArtistId?: string | null; // String
    Title?: string | null; // String
  }
  Artist: { // root type
    Albums?: Array<NexusGenRootTypes['Album'] | null> | null; // [Album]
    ArtistId?: string | null; // String
    Name?: string | null; // String
  }
  Mutation: {};
  Query: {};
  Subscription: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Album: { // field return type
    Artist: NexusGenRootTypes['Artist'] | null; // Artist
    ArtistId: string | null; // String
    Title: string | null; // String
  }
  Artist: { // field return type
    Albums: Array<NexusGenRootTypes['Album'] | null> | null; // [Album]
    ArtistId: string | null; // String
    Name: string | null; // String
  }
  Mutation: { // field return type
    updateArtist: boolean | null; // Boolean
  }
  Query: { // field return type
    artists: Array<NexusGenRootTypes['Artist'] | null> | null; // [Artist]
    hello: string | null; // String
  }
  Subscription: { // field return type
    artistChanges: NexusGenRootTypes['Artist'] | null; // Artist
  }
}

export interface NexusGenFieldTypeNames {
  Album: { // field return type name
    Artist: 'Artist'
    ArtistId: 'String'
    Title: 'String'
  }
  Artist: { // field return type name
    Albums: 'Album'
    ArtistId: 'String'
    Name: 'String'
  }
  Mutation: { // field return type name
    updateArtist: 'Boolean'
  }
  Query: { // field return type name
    artists: 'Artist'
    hello: 'String'
  }
  Subscription: { // field return type name
    artistChanges: 'Artist'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    updateArtist: { // args
      ArtistId?: number | null; // Int
      Name?: string | null; // String
    }
  }
  Subscription: {
    artistChanges: { // args
      ArtistId?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}